### ISSUE TITLE
Exception when I type lein cljsbuild once

### ISSUE THREAD

**Issue by cocodrino** [djhworld/testproject#1]
Hi daniel..I've followed your tutorial and download this project..I run lein deps and this download all dependencies, but when I type cljsbuild once I get:

Exception in thread "main" java.lang.NullPointerException (NO_SOURCE_FILE:0)
        at clojure.lang.Compiler.eval(Compiler.java:5440)
        at clojure.lang.Compiler.eval(Compiler.java:5391)
        at clojure.core$eval.invoke(core.clj:2382)
        at clojure.main$eval_opt.invoke(main.clj:235)
        at clojure.main$initialize.invoke(main.clj:254)
        at clojure.main$script_opt.invoke(main.clj:270)
        at clojure.main$main.doInvoke(main.clj:354)
        at clojure.lang.RestFn.invoke(RestFn.java:483)
        at clojure.lang.Var.invoke(Var.java:381)
        at clojure.lang.AFn.applyToHelper(AFn.java:180)
        at clojure.lang.Var.applyTo(Var.java:482)
        at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
        at leiningen.compile$eval_in_project.doInvoke(compile.clj:162)
        at clojure.lang.RestFn.invoke(RestFn.java:491)
        at leiningen.cljsbuild$run_local_project.invoke(cljsbuild.clj:86)
        at leiningen.cljsbuild$run_compiler.invoke(cljsbuild.clj:94)
        at leiningen.cljsbuild$cljsbuild.invoke(cljsbuild.clj:152)
        at clojure.lang.Var.invoke(Var.java:369)
        at clojure.lang.AFn.applyToHelper(AFn.java:165)
        at clojure.lang.Var.applyTo(Var.java:482)
        at clojure.core$apply.invoke(core.clj:542)
        at leiningen.core$apply_task.invoke(core.clj:219)
        at leiningen.core$_main.doInvoke(core.clj:285)
        at clojure.lang.RestFn.applyTo(RestFn.java:140)
        at clojure.core$apply.invoke(core.clj:542)
        at leiningen.core$_main.invoke(core.clj:288)
        at user$eval153.invoke(NO_SOURCE_FILE:1)
        at clojure.lang.Compiler.eval(Compiler.java:5424)
        ... 11 more

I've tried several times, first with my own project and with this github repo..what am I doing wrong??..I hope you can help me...thanks daniel

**Comment by cocodrino** [comment]
Hi...me again...I've upgrade my leiningen version to the latest version..I'm using windows...now when I try I get this:

lein cljsbuild once
Downloading: cljsbuild/cljsbuild/0.0.13/cljsbuild-0.0.13.pom from repository central at http://repo1.maven.org/maven2
Unable to locate resource in repository
[INFO] Unable to find resource 'cljsbuild:cljsbuild:pom:0.0.13' in repository central (http://repo1.maven.org/maven2)
Downloading: cljsbuild/cljsbuild/0.0.13/cljsbuild-0.0.13.pom from repository clojars at http://clojars.org/repo/
Transferring 2K from clojars
Downloading: cljsbuild/cljsbuild/0.0.13/cljsbuild-0.0.13.jar from repository central at http://repo1.maven.org/maven2
Unable to locate resource in repository
[INFO] Unable to find resource 'cljsbuild:cljsbuild:jar:0.0.13' in repository central (http://repo1.maven.org/maven2)
Downloading: cljsbuild/cljsbuild/0.0.13/cljsbuild-0.0.13.jar from repository clojars at http://clojars.org/repo/
Transferring 4K from clojars
Compiling ClojureScript
Compiling resources/public/js/cljs.js from src-cljs...
WARNING: The form (. this toString) is no longer a property access. Maybe you meant (. this -toString) instead?
WARNING: The form (. this toString) is no longer a property access. Maybe you meant (. this -toString) instead?
WARNING: The form (. (js-keys hashobj) sort) is no longer a property access. Maybe you meant (. (js-keys hashobj) -sort) instead?
WARNING: The form (. this toString) is no longer a property access. Maybe you meant (. this -toString) instead?
WARNING: The form (. this toString) is no longer a property access. Maybe you meant (. this -toString) instead?
WARNING: The form (. (js-keys hashobj) sort) is no longer a property access. Maybe you meant (. (js-keys hashobj) -sort) instead?
 Failed!
←[31mjava.lang.NullPointerException: ←[39m←[31m←[39m
←[34m      Compiler.java:869 com.google.javascript.jscomp.Compiler.newTracer←[39m
←[34m      Compiler.java:516 com.google.javascript.jscomp.Compiler.compile←[39m
←[34m       (Unknown Source) sun.reflect.NativeMethodAccessorImpl.invoke0←[39m
←[34m       (Unknown Source) sun.reflect.NativeMethodAccessorImpl.invoke←[39m
←[34m       (Unknown Source) sun.reflect.DelegatingMethodAccessorImpl.invoke←[39m
←[34m       (Unknown Source) java.lang.reflect.Method.invoke←[39m
←[36m      Reflector.java:92 clojure.lang.Reflector.invokeMatchingMethod←[39m
←[36m      Reflector.java:30 clojure.lang.Reflector.invokeInstanceMethod←[39m
←[32m        closure.clj:649 cljs.closure/optimize←[39m
←[36m        RestFn.java:139 clojure.lang.RestFn.applyTo←[39m
←[35m           core.clj:602 clojure.core/apply←[39m
←[32m        closure.clj:840 cljs.closure/build←[39m
←[32m            core.clj:71 cljsbuild.core/compile-cljs←[39m
←[32m           core.clj:179 cljsbuild.core/run-compiler←[39m
←[33m       NO_SOURCE_FILE:1 user/eval2057[fn]←[39m
←[32m           core.clj:154 cljsbuild.core/in-threads[fn]←[39m
←[35m          core.clj:1817 clojure.core/binding-conveyor-fn[fn]←[39m
←[36m            AFn.java:18 clojure.lang.AFn.call←[39m
←[34m       (Unknown Source) java.util.concurrent.FutureTask$Sync.innerRun←[39m
←[34m       (Unknown Source) java.util.concurrent.FutureTask.run←[39m
←[34m       (Unknown Source) java.util.concurrent.ThreadPoolExecutor.runWorker←[39m
←[34m       (Unknown Source) java.util.concurrent.ThreadPoolExecutor$Worker.run←[39m
←[34m       (Unknown Source) java.lang.Thread.run←[39m

hope you can understand what this mean...thanks man...

**Comment by djhworld** [comment]
Hi cocodrino, Thanks for you interest in my post

I made a bit of an error in the blog concerning the fact that you need to check out a different branch for this project

```
git clone https://djhworld@github.com/djhworld/testproject.git
git checkout twitter-post2
```

However that aside, a similar issue was raised for the project on my [previous post](https://github.com/djhworld/djhworld.github.com/issues/1) ( scroll down a bit)

The common factor between your issue and his is you're both on Windows which might be causing the problem. 

I'm on a Windows machine at the moment (at work) and I've run the clojurescript compiler OK and run `lein run` without any issues - however I am doing this via Cygwin.

Could you try using cygwin or a *nix based box?
